[package]
name = "libsignal-net"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[features]
test-support = []

[dependencies]
attest = { path = "../attest" }
libsignal-core = { path = "../core" }
libsignal-protocol = { path = "../protocol" }
libsignal-svr3 = { path = "../svr3" }

async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitstream-io = "1.10.0"
boring-signal = { workspace = true }
bytes = "1.4.0"
const-str = { version = "0.5.6", features = ["std"] }
derive-where = { workspace = true }
displaydoc = { workspace = true }
either = "1.10.0"
futures-util = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["http2", "client"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
indexmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
nonzero_ext = { workspace = true }
num_enum = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
rustls = { version = "0.23.4", default-features = false, features = ["ring", "std", "tls12"] }
rustls-platform-verifier = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
snow = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros"] }
tokio-boring-signal = { workspace = true }
tokio-socks = "0.5.2"
tokio-stream = "0.1.14"
tokio-tungstenite = "0.23.0"
tokio-util = "0.7.9"
tungstenite = { version = "0.23.0", features = ["url"] }
url = "2.4.1"
uuid = { workspace = true }
zerocopy = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = "2.1"
env_logger = { workspace = true }
hex-literal = { workspace = true }
hickory-proto = "0.24.1"
lazy_static = { workspace = true }
proptest = { workspace = true }
proptest-state-machine = "0.1.0"
rcgen = "0.13.0"
snow = { workspace = true, features = ["default-resolver"] }
socks5-server = "0.10.1"
test-case = { workspace = true }
tls-parser = "0.11.0"
tokio = { workspace = true, features = [
    "test-util",
    "io-std",
    "rt-multi-thread",
] }
warp = { version = "0.3.6", features = ["tls"] }

[[example]]
name = "svr3"
required-features = ["test-support"]

[[example]]
name = "svr3_prop_test"
required-features = ["test-support"]

[[example]]
name = "chat_smoke_test"
required-features = ["test-support"]

[[test]]
name = "svr3_migration"
required-features = ["test-support"]
